### PR TITLE
chapter 7 init and first solution

### PR DESCRIPTION
**Pull request by AmmarCSE**
This pull request initiates the chapter 7 directory and provides the solution to the first question.

### CODE REVIEW

**Comment by AmmarCSE** [comment]
bump.

Sorry, not to seem pushy. 
I just want to make sure it is fine so I can continue to contribute.

**Comment by asaph** [comment]
@AmmarCSE Please continue to contribute. I'll do my best to make sure your PRs are reviewed in a timely manner.

**Comment by diadical** [comment]
@AmmarCSE thank you for the submission.

Please run the linting and test with changes to the solution. Your changes cause 241 lint errors when I do that. Many of these are stylistic but that's on purpose as it's easier to work on a codebase where the style guidelines are aligned. Some are also more significant like unused and even undeclared variables.

Also please use the test infrastructure that is in place to demonstrate the solution, this is preferable as it allows for validation of the entire codebase without individually testing each answer. It also allows people to experiment with changes and quickly validate that they don't do something erroneous and is certainly far easier to understand than interpreting a bunch of console output. I understand this is more of an OOP design question but it can still be validated in this way and will make your design decisions clearer by specifically testing your expectations.

**Comment by AmmarCSE** [comment]
Hey there @diadical.

I just pushed a commit which resolves the lint errors except the 'no-console' errors only because I feel the console logs are integral into running the actual solution.

Now, with regards to tests, I have skimmed some of the current tests. However, I couldnt decide whats a minimal criteria for acceptable tests. Should I unit test each and every method in the classes in my solution? What if the testing is simply too tedious considering some of this blackjack game is based on 'random' numbers. 

The solution it self works if you run the main javascript file. Ive compared it with the official java solution and they are very alike. If testing is a must, can you suggest a more clear route I should take in testing?

**Comment by AmmarCSE** [comment]
Bump.

Hey there @diadical, @asaph.

Can I please get an answer with regards to the question in my previous comment on what are acceptable tests? Will simple _describe_ tests suffice?

**Comment by diadical** [comment]
@AmmarCSE since these are more design questions about OOP rather than algorithmic I'm happy to accept this version. I think that tests would make it far easier for others to validate changes and better document your intent - I don't want to prolong pulling this longer.

Thanks for correcting the linting issues. I'll add some eslint exclusions for the remaining errors around console usage - which is required for your solution.

**Pull request merged**
