### PR TITLE
chapter 7 question 2 with fixed lint errors

### PR DESCRIPTION
**Pull request by AmmarCSE**

### CODE REVIEW

**Comment by AmmarCSE** [comment]
Hey there @diadical 

Thanks for accepting my previous pull request for chapter 7, question 1.

I have just submitted question 2 and look forward to contributing even more.

In the meantime, please let me know if there are any issues or if theres anything I could do.

Thanks

**Comment by AmmarCSE** [comment]
@diadical @asaph 

bump. :-)

**Comment by diadical** [comment]
Happy new year! Apologies for not getting to this sooner - there seem to be a few log files attached to the request was that intentional?

Otherwise I'm happy to approve the request.

@asaph the time I have available to look at these at the moment is really limited. @AmmarCSE seems to be a keen contributor can I suggest he be added as a collaborator and continue improvements to this repo?

**Comment by AmmarCSE** [comment]
@diadical @asaph 

Whoops! Need to pay more attention and do git status before adding/committing.

Yes, I would love to be added as a collaborator. My only intention is to provide es6 solutions to questions that don't yet have answers.

Do let me know as I intend to complete the rest of chapter 7.

**Comment by asaph** [comment]
@diadical I've added @AmmarCSE as a collaborator on the Javascript ES6 solutions repo. Thank you @AmmarCSE for your contributions!

**Pull request merged**
